version: "3.8"

volumes:
  sc-volume:
    name: sc-volume
  database_mysql:
    
networks:
  sc-network:
    name: sc-network

services:
  tasks-service:
    build:
      context: ./tasks-service
      dockerfile: Dockerfile
    container_name: tasks-service
    ports:
      - "${TASKS_HTTP_PORT}:${TASKS_HTTP_PORT}"
    environment:
      - DB_DRIVER=${TASKS_DB_DRIVER}
      - DB_HOST=${MYSQL_HOST}
      - DB_PORT=${MYSQL_PORT}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_TASKS_DB_NAME}
      - HTTP_PORT=:${TASKS_HTTP_PORT}
      - HTTP_PATH=/${TASKS_HTTP_PATH}
    restart: on-failure
    volumes:
      - ./:/app
    depends_on:
      - mysql-sc
    networks:
      - sc-network

  mysql-sc:
    image: mysql:5.7
    container_name: "${MYSQL_HOST}"
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    environment:
      - MYSQL_ROOT_HOST=${MYSQL_HOST} 
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_TASKS_DB_NAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - sc-network
