################################################################
# Middlewares
################################################################

[http.middlewares]

  ## Forward Auth
  [http.middlewares.fwd-auth.forwardAuth]
    address = "http://localhost/auth"
    authResponseHeaders = ["X-User-Id", "X-User-Role"]
  ## Strip Prefix
  [http.middlewares.task-stripprefix.stripPrefix]
    prefixes = ["/task"]