// Code generated by MockGen. DO NOT EDIT.
// Source: task_publisher.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	task "github.com/pedroquerido/sword-challenge/tasks-service/pkg/task"
)

// MockPublisher is a mock of Publisher interface.
type MockPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherMockRecorder
}

// MockPublisherMockRecorder is the mock recorder for MockPublisher.
type MockPublisherMockRecorder struct {
	mock *MockPublisher
}

// NewMockPublisher creates a new mock instance.
func NewMockPublisher(ctrl *gomock.Controller) *MockPublisher {
	mock := &MockPublisher{ctrl: ctrl}
	mock.recorder = &MockPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisher) EXPECT() *MockPublisherMockRecorder {
	return m.recorder
}

// PublishTaskCreated mocks base method.
func (m *MockPublisher) PublishTaskCreated(task *task.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishTaskCreated", task)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishTaskCreated indicates an expected call of PublishTaskCreated.
func (mr *MockPublisherMockRecorder) PublishTaskCreated(task interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishTaskCreated", reflect.TypeOf((*MockPublisher)(nil).PublishTaskCreated), task)
}
