# Golang build image
FROM golang:1.15 as builder

# Maintainer
LABEL maintainer="Pedro Querido <pedroquerido14@gmail.com>"

RUN mkdir /app

ADD . /app

WORKDIR /app

RUN go mod download

CMD CGO_ENABLED=0 go test -v  ./...